import Head from "next/head";
import React, { useState, useEffect } from "react";
import Main from "../components/Main";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import Navbar from "@/components/Navbar";
import { Product } from "@/types/Products";
import CardMaterial from "@/components/material/CardMaterial";

export default function Home() {
  const [data, setData] = useState<Product[]>([]);
  console.log(data);

  useEffect(() => {
    fetch("http://localhost:3001/products")
      .then((res) => res.json())
      .then((data) => setData(data));
  }, [setData]);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} `}>
        <div style={{ display: "flex", gap: "20px", flexWrap: "wrap" }}>
          {data.map((product, index) => {
            return (
              <CardMaterial
                key={index}
                name={product.name}
                price={product.price}
                image={product.image}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
